<a href="https://colab.research.google.com/github/pallab99/Numpy/blob/main/Numpy_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**The Basics**

In [2]:
import numpy as np
#1d array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
# 2d array
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#Get dimension
a.ndim
#b.ndim

1

In [ ]:
#get Shape
b.shape

(2, 4)

In [ ]:
#get type
b.dtype


dtype('int64')

In [ ]:
#get size
a.itemsize
b.size

8

**Accessing / Changing specific elements , rows , columns , etc**


In [3]:
aa=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(aa)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
#get a specefic element [r,c]
aa[1,4]

12

In [5]:
#get a specefic row or col
#aa[0,:]
#aa[1,:]
aa[:,0]

array([1, 8])

In [6]:
#little more fancy [row,start_index:end_index:stepsize]
aa[1,1:6:1]

array([ 9, 10, 11, 12, 13])