<a href="https://colab.research.google.com/github/pallab99/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
#1d array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
# 2d array
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
a.ndim
#b.ndim

1